### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Manu99it** [kurema/BookViewerApp3#1]
Hello :)
I've tried your app by downloading it in Microsoft Store, and also, I reviewed it. How I wrote in the review, it opens pdf binded images without losing any bit of quality. Most readers don't do that, neither Adobe Acrobat or Xodo. Also it's very simple and fast. So i would thanking you making an italian translation. If you are not going to do any big change in super fast time, I'm going to translate values of Resources.lang-en-US.resw and making a pull request to add "Resources.lang-it-IT.resw"

**Comment by kurema** [comment]
Thank you for trying my app.

But I haven't published this on the store.
There is only old version([BookViewerApp](https://github.com/kurema/BookViewerApp)) on Microsoft Store.
Maybe someone else published it which I think is unlikely or you are using old version.

About PDF, I haven't done anything tricky in the old version.
There is PDF rasterizing API(Windows.Data.Pdf) which Microsoft implements, and I just use it.
In this version, I updated my code to use 4x size to fix some issue.
Maybe that's why PDF looks good.

I have currently no plan to translate it in Italy.
But now I know you want it, I think it's good idea.
If I do that, I have to use machine translation from English and result would be very poor.
You are very welcome for pull request.

**Comment by kurema** [comment]
There is some minor note for pull request.
Only #1-3 is important, others is TL;DR.

1. There is two Resources.lang-en-US.resw. One is [here](https://github.com/kurema/BookViewerApp3/tree/master/BookViewerApp/Resource), the other is [here](https://github.com/kurema/BookViewerApp3/tree/master/FileExplorerControl/Resource).
2. License should be CC0 or MIT. CC0 is better for me. Do not use something like GPL.
3. Your name will be in README.md, Resources.lang-it-IT.resw (in ) and info screen in the app. You can choose your name and URL to be shown. But I don't want copyright note in [LICENSE](https://github.com/kurema/BookViewerApp3/blob/master/LICENSE) to change.
4. I'm planning to publish BookViewerApp3 as another app in Windows Store. Your resource will be used in both version.
5. There are some values which is not used either/neither of BookViewerApp or/nor BookViewerApp3. Some of translation would be never seen by any users.
6. If I add resource in future update, I will have to translate by myself using machine translation. This may look strange for Italian user.

**Comment by Manu99it** [comment]
Good! Well yes, I surely was using the old version published by someone else because I didn't compile it. I've seen that you're just using the implemented api, for that I'm like "what!?" when I see others app to do a bad pdf visualization, chromium edge included (I hope they are going to change that, old edge was 100 times better as e-reader😅). Today I'm going to translate both these files. As per 2-3 there isn't any problem, I want just see the app translated so I'll keep the code how it is, license included. I'm not interested in name also but if you add it just use wathever you want, name or nick is the same. 4 No problem. 5 just lol why there are that😂. 6 if I'll see some changes I'll try to keep translation updated. 7 app is yours so take your time. And many similar apps are to pay, so you could just make this paid aswell to remunerate your work

**Comment by kurema** [comment]
Files are imported and transformed into xlf (I'm using Multilingual App Toolkit now).
